name: EnderChat
main: net.gauragangur.EnderChat.EnderChat
version: 0.1
author: TheNokar
description: EnderChat easy chat plugin
depend: [Vault]
permissions:
  enderchat.color:
     description: Color
     default: op
commands:
  tell:
     usages: /tell <player> <msg>
  r:
     usages: /r <msg>
